export const GET_CITIES = "GET_CITIES"
export const GET_ITINERARY = "GET_ITINERARY"
export const IS_FETCHING = 'IS_FETCHING'
export const IS_FETCHING_ITINERARY = 'IS_FETCHING_ITINERARY'
export const SESSION_ON = 'SESSION_ON'
export const SESSION_OFF = 'SESSION_OFF'
export const NO_ERRORS = 'NO_ERRORS'
export const ADD_OR_DEL_FAV = 'ADD_OR_DEL_FAV'
export const GET_FAVOURITES = 'GET_FAVOURITES'


