export const GET_CITIES = "GET_CITIES"
export const GET_ITINERARY = "GET_ITINERARY"
export const IS_FETCHING = 'IS_FETCHING'
export const IS_FETCHING_ITINERARY = 'IS_FETCHING_ITINERARY'
export const SESION_ON = 'SESION_ON'
export const SESION_OFF = 'SESION_OFF'